import pandas as pd
import json

def generate_crash_csv(input_json='report.json', output_csv='crash_reports.csv'):
    try:
        # Read the JSON report generated by your main engine
        df = pd.read_json(input_json)
        # Save to CSV - index=False keeps it clean for Excel/Google Sheets
        df.to_csv(output_csv, index=False)
        print(f"✅ Success: {output_csv} created with {len(df)} records.")
    except Exception as e:
        print(f"❌ Error converting to CSV: {e}")

if __name__ == "__main__":
    generate_crash_csv()
